version: '3.7'

services:
  news_data:
    image: sonishreyas/news-api-service
    command: flask run
    volumes:
      - ./app:/home/app
      - ./configs:/home/app/configs
    expose:
      - 5000
    environment:
      - FLASK_RUN_PORT=5000
    env_file:
      - ./configs/.env.dev
    restart: always 


  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./configs/nginx-prod-cors:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - news_data
    restart: always